 development:
   adapter: postgresql
   database: etsy_development
   pool: 5
   timeout: 5000
 test:
   adapter: postgresql
   database: etsy_test
   pool: 5
   timeout: 5000
 production:
   adapter: postgresql
   database: etsy_production
   pool: 5
   timeout: 5000
